### ISSUE TITLE
Implement array-count-search-occurances

### ISSUE THREAD

**Issue by FarshadJanmohammadi** [Code-Coterie-Team/array-count-search-occurances#1]
<img width="900" alt="20-02-array-count-search-occurances" src="https://github.com/user-attachments/assets/89c4d4f2-c360-4886-8e0e-0e4f6ee46654">

**Comment by arezooamiri** [comment]
Can you explain more about this task ?!
I don't know about search occurrences

**Comment by FarshadJanmohammadi** [comment]
> Can you explain more about this task ?!
> I don't know about search occurrences

Hi, Arezou, create function that take one array besed on parameter, then calculate how much repeat word in array, for example give such array ["cow","cat","cow"], expect result 
cow =2
Cat=1

**Comment by arezooamiri** [comment]
Tanks,I got it
